export enum AdminActionTargetType {
  DRIVER = 'DRIVER',
}

export enum AdminAuditAction {
  APPROVE_DRIVER = 'APPROVE_DRIVER',
  REJECT_DRIVER = 'REJECT_DRIVER',
  BLOCK_DRIVER = 'BLOCK_DRIVER',
  UNBLOCK_DRIVER = 'UNBLOCK_DRIVER',
  APPROVE_DOCUMENT = 'APPROVE_DOCUMENT',
  REJECT_DOCUMENT = 'REJECT_DOCUMENT',
}
